// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl7QpjKVNymNorXmLEWRUPDWKYDXhkJbc',
    appId: '1:356398444430:web:9c0f3987c5febf84437edf',
    messagingSenderId: '356398444430',
    projectId: 'meetm-3123c',
    authDomain: 'meetm-3123c.firebaseapp.com',
    storageBucket: 'meetm-3123c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARv7M7F6FUTuQNS9U_Z_3KNjLHsQXqGS8',
    appId: '1:356398444430:android:d3fe576077b40f79437edf',
    messagingSenderId: '356398444430',
    projectId: 'meetm-3123c',
    storageBucket: 'meetm-3123c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs64aXEfpgBmCX1BxNYj7MsSwpvY3irX8',
    appId: '1:356398444430:ios:9c6740d7f0fe8417437edf',
    messagingSenderId: '356398444430',
    projectId: 'meetm-3123c',
    storageBucket: 'meetm-3123c.appspot.com',
    iosBundleId: 'com.example.meetMentorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs64aXEfpgBmCX1BxNYj7MsSwpvY3irX8',
    appId: '1:356398444430:ios:5c1ce0fdf778a1e6437edf',
    messagingSenderId: '356398444430',
    projectId: 'meetm-3123c',
    storageBucket: 'meetm-3123c.appspot.com',
    iosBundleId: 'com.example.meetMentorApp.RunnerTests',
  );
}
